# Generated by Django 2.0 on 2021-12-08 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0003_auto_20180605_0842'),
        ('census', '0001_initial'),
        ('voter',  '0003_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='name',
            field=models.TextField(default='undefined census', unique=True),
        ),
        migrations.AddField(
            model_name='census',
            name='voter_ids',
            field=models.ManyToManyField(to='census.Voter'),
        ),
        migrations.AddField(
            model_name='census',
            name='voting_ids',
            field=models.ManyToManyField(to='voting.Voting'),
        ),
        migrations.AlterUniqueTogether(
            name='census',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='census',
            name='voter_id',
        ),
        migrations.RemoveField(
            model_name='census',
            name='voting_id',
        ),
    ]
