# Generated by Django 2.0 on 2021-12-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_census_votersids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='census',
            old_name='votersIds',
            new_name='voters_ids',
        ),
    ]
