# Generated by Django 2.0 on 2021-12-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_auto_20211219_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='census',
            old_name='voters_ids',
            new_name='voter_ids',
        ),
    ]
