# Generated by Django 2.0 on 2021-12-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0008_auto_20211219_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='genero',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='location',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
