# Generated by Django 2.0 on 2022-01-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0009_auto_20211228_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='voter_ids',
            field=models.ManyToManyField(to='census.Voter'),
        ),
    ]
