# Generated by Django 2.0 on 2022-01-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0010_auto_20220106_1704'),
        ('census', '0010_auto_20220104_1628'),
    ]

    operations = [
    ]
