# Generated by Django 2.0 on 2022-01-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0010_auto_20220102_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='genero',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='location',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
