# Generated by Django 2.0 on 2022-01-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0010_auto_20220103_2259'),
        ('census', '0011_merge_20220106_1709'),
    ]

    operations = [
    ]
