# Generated by Django 2.0 on 2022-01-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0012_merge_20220106_2225'),
        ('census', '0011_auto_20220104_1640'),
    ]

    operations = [
    ]
