# Generated by Django 2.0 on 2022-01-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0013_merge_20220107_1639'),
        ('census', '0010_auto_20220107_1802'),
    ]

    operations = [
    ]
