# Generated by Django 2.0 on 2021-12-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
