# Generated by Django 2.0 on 2021-12-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='tipo',
        ),
    ]
